name: 🔒 Alwaysdata Keep-Alive

on:
  schedule:
  - cron: "0 0 1 * *" # Ejecuta el workflow el día 1 de cada mes a medianoche UTC
  workflow_dispatch:
    # Permite ejecución manual

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
    - name: 📦 Checkout Repository
      uses: actions/checkout@v3

    - name: 💿 Install Node.js v20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Check Necesary Secrets
      run: |
        if [ -z "${{ secrets.ALWAYSDATA_USER }}" ]; then
          echo "Error: ALWAYSDATA_USER not defined"
          exit 1
        fi
        if [ -z "${{ secrets.ALWAYSDATA_PASS }}" ]; then
          echo "Error: ALWAYSDATA_PASS not defined"
          exit 1
        fi
        echo "CI=${CI}"
        echo "ALWAYSDATA_USER=${{ secrets.ALWAYSDATA_USER }}"

    - name: Cache Bun modules
      uses: actions/cache@v3
      with:
        path: ~/.bun
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: 🍙 Bun Setup
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Verificar estructura de archivos
      run: |
        if [ ! -d "cypress/support/config" ]; then
          echo "Directory cypress/support/config does not exist."
          exit 1
        fi
        if [ -z "$(ls -A cypress/support/config)" ]; then
          echo "Directory cypress/support/config is empty."
          exit 1
        fi
        echo "Directory cypress/support/config exists and is not empty."
        find cypress/support/config

    - name: Run Alwaysdata Cron Job
      env:
        ALWAYSDATA_USER: ${{ secrets.ALWAYSDATA_USER }}
        ALWAYSDATA_PASS: ${{ secrets.ALWAYSDATA_PASS }}
      run: |
        bun cypress run --config-file cypress.config.cron.ts --browser electron --spec 'cypress/Tests/utils/AlwaysData-cron.cy.ts'
