name: 🔒 Alwaysdata Keep-Alive

on:
  schedule:
  - cron: "0 0 1 * *" # Ejecuta el workflow el día 1 de cada mes a medianoche UTC
  workflow_dispatch:
    # Permite ejecución manual

env:
  ALWAYSDATA_USER: ${{ secrets.ALWAYSDATA_USER }}
  ALWAYSDATA_PASS: ${{ secrets.ALWAYSDATA_PASS }}

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
    - name: 📦 Checkout Repository
      uses: actions/checkout@v3

    - name: 💿 Install Node.js v20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Check Necesary Secrets
      run: |
        if [ -z "$ALWAYSDATA_USER" ] || [ -z "$ALWAYSDATA_PASS" ]; then
          echo "Error: ALWAYSDATA_USER or ALWAYSDATA_PASS is not defined"
          exit 1
        fi

    - name: Cache Bun modules
      uses: actions/cache@v3
      with:
        path: ~/.bun
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: 🍙 Bun Setup
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Run Alwaysdata Cron Job
      run: |
        bun run cypress run --browser electron --config-file=cypress.config.cron.ts --spec=cypress/Tests/utils/AlwaysData-cron.cy.ts
